### ISSUE TITLE
Docker Container crashes

### ISSUE THREAD

**Issue by derlbear** [mikenye/docker-virtualradarserver#20]
Hi,
I'm trying to host a docker container on my Oracle server.

This is my docker-compose.yml (I'm using traefik):
```
version: '2.0'

volumes:
  vrsconfig:

services:
  virtualradarserver:
    image: mikenye/virtualradarserver:latest
    tty: true
    container_name: vrs
    restart: always
    volumes:
      - /opt/docker/virtualradarserver/vrsconfig:/config
    environment:
      - USERNAME=MYUSERNAME
      - PASSWORD='MYPASSWORD'
      - BASESTATIONHOST=readsb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.virtualradarserver.entrypoints=websecure"
      - "traefik.http.routers.virtualradarserver.rule=Host(`vrs.MYSUBDOMAIN.duckdns.org`)"
      - "traefik.http.routers.virtualradarserver.tls=true"
      - "traefik.http.routers.virtualradarserver.tls.certresolver=http_resolver"
      - "traefik.http.routers.virtualradarserver.service=virtualradarserver"
      - "traefik.http.services.virtualradarserver.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.virtualradarserver.middlewares=default@file"
networks:
  proxy:
    external: true
```

When I start the container, I receive the following:

```
user@ubuntu:/opt/docker/virtualradarserver$ docker compose up
[+] Running 2/2
 ✔ Network virtualradarserver_default  Created                                                                                                                                          0.1s
 ✔ Container vrs                       Created                                                                                                                                          0.0s
Attaching to vrs
vrs  | [s6-init] making user provided files available at /var/run/s6/etc...
vrs  | exited 0.
vrs  | [s6-init] ensuring user provided files have correct perms...
vrs  | exited 0.
vrs  | [fix-attrs.d] applying ownership & permissions fixes...
vrs  | [fix-attrs.d] done.
vrs  | [cont-init.d] executing container initialization scripts...
vrs  | [cont-init.d] 01-sanity_check: executing...
vrs  | WARNING: TZ environment variable not set
vrs  | [cont-init.d] 01-sanity_check: exited 0.
vrs  | [cont-init.d] 02-vrs_extras: executing...
vrs  | Installing operator flags...
vrs  | cp: target '/config/operatorflags' is not a directory
vrs  | cp: target '/config/operatorflags' is not a directory
vrs  | chown: cannot access '/config/operatorflags': No such file or directory
vrs  | Installing silhouettes...
vrs  | cp: target '/config/silhouettes/' is not a directory
vrs  | chown: cannot access '/config/silhouettes': No such file or directory
vrs  | [cont-init.d] 02-vrs_extras: exited 1.
vrs  | [cont-finish.d] executing container finish scripts...
vrs  | [cont-finish.d] done.
vrs  | [s6-finish] waiting for services.
vrs  | [s6-finish] sending all processes the TERM signal.
vrs  | [s6-finish] sending all processes the KILL signal and exiting.
vrs exited with code 0

```
What am I doing wrong?
