### ISSUE TITLE
Running fails, directories not available

### ISSUE THREAD

**Issue by klara31** [mikenye/docker-virtualradarserver#4]
Running the container fails with the following error:
```
# docker-compose up vrs
Pulling vrs (mikenye/virtualradarserver:latest)...
latest: Pulling from mikenye/virtualradarserver
54fec2fa59d0: Pull complete
583304b1b9b3: Pull complete
4d67f55efeff: Pull complete
48aabf0914f5: Pull complete
74a3d1988095: Pull complete
Digest: sha256:b7deae8a62ac1fb056f27f9919b9f959dc4d93cd60827dd4f37bc527fd16f5b8
Status: Downloaded newer image for mikenye/virtualradarserver:latest
Creating vrs ... done
Attaching to vrs
vrs             | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
vrs             | [s6-init] ensuring user provided files have correct perms...exited 0.
vrs             | [fix-attrs.d] applying ownership & permissions fixes...
vrs             | [fix-attrs.d] done.
vrs             | [cont-init.d] executing container initialization scripts...
vrs             | [cont-init.d] 01-vrs: executing...
vrs             | Installing operator flags...
vrs             | cp: target '/config/operatorflags' is not a directory
vrs             | cp: target '/config/operatorflags' is not a directory
vrs             | chown: cannot access '/config/operatorflags': No such file or directory
vrs             | Installing silhouettes...
vrs             | cp: target '/config/silhouettes/' is not a directory
vrs             | chown: cannot access '/config/silhouettes': No such file or directory
vrs             | [cont-init.d] 01-vrs: exited 1.
vrs             | [cont-finish.d] executing container finish scripts...
vrs             | [cont-finish.d] done.
vrs             | [s6-finish] waiting for services.
vrs             | [s6-finish] sending all processes the TERM signal.
vrs             | [s6-finish] sending all processes the KILL signal and exiting.
```

My docker-compose looks as follows:
```yaml
version: '3.7'
services:
  vrs:
    image: mikenye/virtualradarserver:latest
    container_name: vrs
    tty: true
    volumes:
    - ${USERDIR}/virtualradarserver:/config
    ports:
    - 8787:8080
    environment:
    - TZ=${TZ}
    - BASESTATIONHOST=192.168.10.6
    - USERNAME=admin
    - PASSWORD=admin
    network_mode: bridge
    restart: unless-stopped
```
When manually adding the two directories, docker continues, but does download and install each time the operator_flags, which take quite some time...

**Comment by mikenye** [comment]
I've set `/config` as a `VOLUME` in the image's `Dockerfile`.

As-per the [Dockerfile `VOLUME` reference](https://docs.docker.com/engine/reference/builder/#volume):

> The docker run command initializes the newly created volume with any data that exists at the specified location within the base image.

However, if you check out https://github.com/moby/moby/issues/17470, you'll see that for bind mounts (as-per your docker-compose above), docker won't clobber the contents of a local path, however it does work for named volumes.

I've had success with the following docker-compose:

```yaml
version: '2.0'

networks:
  adsbnet:

volumes:
  vrsconfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/adsb/vrs'

services:
  virtualradarserver:
    image: vrstest:latest
    tty: true
    container_name: vrs
    restart: always
    volumes:
      - vrsconfig:/config
    ports:
      - 8077:8080
    environment:
      - USERNAME=vrsadmin
      - PASSWORD=vrsadmin
      - BASESTATIONHOST=readsb
    networks:
      - adsbnet
```

I'm just re-building the `mikenye/virtualradarserver:latest` - this takes quite a while for this image but I'll report back here when it's ready for you to test.
